### ISSUE TITLE
【系统改进】deployment/models/pre_loaded.txt 改为 YAML 格式

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#1045]
**现状**
> 当前的现状是什么（当前的行为、设计、架构）？

**系统改进的目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

**系统改进的实施方案**
> 详细提供该系统改进的实施方案

**Comment by donggangcj** [comment]
@yzhao-2023  确认一下是YAML还是markdown
