### ISSUE TITLE
【需求】CPodManager 须在 MPIJob 中指定 GPU 型号作为 nodeselector

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#169]
**这个功能需求是来解决什么问题？**
![image](https://github.com/NascentCore/3k/assets/142474494/6a9bfdd3-6af0-42cf-a801-8c8f17f998d3)
node label nvidia.com/gpu.product 提供了 GPU 型号
用户在云市场入口指定了该型号
需要在 MPIJob 中指定该型号

**是否在 Kubernetes 平台上，以及版本号**
是/否

**内核版本**
3.xx/4.xx/5.xx

**是否考虑过其他解决方案**
列举考虑过的其他解决方案

**Comment by yzhao-2023** [comment]
https://github.com/NascentCore/3k/blob/main/devops/GPU_MODELS
手动罗列了目前提供的 GPU 型号；建议目前 MVP 阶段，云市场入口直接拷贝上述 model，然后用于前端页面的展示；CPodManager 无需考虑

**Comment by yzhao-2023** [comment]
下一步的改进方案：
https://github.com/NascentCore/3k/issues/170

**Comment by congpeiqing** [comment]
个人理解目前对于MVP非必要，可以延后   @yzhao-2023    @glen-nascentcoreai

**Comment by yzhao-2023** [comment]
不对，此项功能是保证运行的基本要求

没有此功能，用户的训练任务会失败
比如 llama2 在 3090 上会因为现存不足而直接 crash

此项功能实现只需要在 mpijob yaml 中指定 nodeselector，相对简单，如果时间不足，我来顶上
