### ISSUE TITLE
【系统改进】添加 kubeflow training operator 到三千平台

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#195]
**背景**
目前三千平台使用 MPI operator v2，原因是 MPI operator v2 提供了重启计算任务的功能（具体优势还没有评测过）
比如：
* 能够launcher/worker单独retry

为了支持其他类型的任务，需要使用 Kubeflow Training Operator
https://github.com/kubeflow/training-operator

**系统改进提议和目的**

由于两者都定义了 MPIJob CRD，因此直接安装会导致冲突
需要 fork [training-operator](https://github.com/kubeflow/training-operator)，把MPI相关的control loop关掉，去掉MPIJob的CRD，同时使用现有的MPI operator v2。

这样就可以使用 v2 MPI operator 及其他的 training operator

**是否考虑过其他解决方案**
无

**Comment by yzhao-2023** [comment]
解释需要咨询外部专家搞清楚如何实现“把MPI相关的control loop关掉，去掉MPIJob的CRD”

**Comment by yzhao-2023** [comment]
可以开始考虑一下，未来引入更多的 job 类型的其他问题，比如引入 Kubeflow Training Operator：https://github.com/NascentCore/3k/issues/195
需要针对 “Job” 这个概念做一些抽象，建议先观察 mpijob 的详情，结合跟 @glen-nascentcoreai 交流模型分布式训练/推理的需求，相应思考
![image](https://github.com/NascentCore/3k/assets/142474494/5560ec5a-f9e3-4fd2-86fe-4a8e2b3b1810)

**Comment by yzhao-2023** [comment]
联系 @yzhao-2023 与外部专家建立联系

**Comment by sxwl-donggang** [comment]
MPI job使用mpi-operator，training-operator中去掉MPI job，training-operator manager通过参数忽略掉mpi job。

**Comment by glen-nascentcoreai** [comment]
上面的方式去掉Training operator中的MPIJob不知道是不是彻底，可能还需要咨询Terry。
完成后，Training operator和MPI operator（V2）共存，只有MPI operator中有MPIJob CRD及相关。

**Comment by sxwl-donggang** [comment]
通过enable-schema参数配置，可以不开启mpi job相关的controller:https://github.com/kubeflow/training-operator/blob/230bfb453188ecc0e9def4296e75f4bd06707769/cmd/training-operator.v1/main.go#L180
