### ISSUE TITLE
【功能需求】精细调度来支持分布式大模型训练（如 3D 并行调度等，各类要求列在 comments 内）

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#198]
**这个功能需求是来解决什么问题？**
3D 并行：数据、流水线、张量并行要求两层调度
* 数据并行层级：每一个模型训练实例运行完整的模型
* 流水线/张量并行：在上述的单一模型实例上继续切分模型实例到多 GPU（甚至是多机）

调度层面，需要对应模型训练代码与服务器，进行编排

**解决方案**
目前我们还没有具体方案

**Comment by yzhao-2023** [comment]
基于优先级的任务资源和大小任务的协作和兼容

**Comment by sxwl-donggang** [comment]
这里如何分配pod和每个pod的GPU数量需要结合具体节点配置（拓扑）
集群A: 3node*4*GPU 
集群B 3*node*8GPU 
如果用户训练任务需要8GPU运行,在集群A中需要2Pod，每个pod运行在不同节点 ，如果是集群B则只需要在一个节点运行一个pod,如果用户无法感知集群节点配置，则无法合理指定pod数量和每个pod需要几块卡

**Comment by sxwl-donggang** [comment]
对于分布式训练任务，应该需要用户显示指定数据并行、模型并行配置
