### ISSUE TITLE
创建任务详情页面

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#223]
页面应显示训练任务结束后生成模型的上传地址

此要求来自于 2023-10-20 的 DEMO 日演示；我们任务提交的任务的详情页，应该包含上传训练好的输出的模型链接

**Comment by jimgreat666** [comment]
目前与亚雄周五1v1对话时，方案是在目前的详情页上添加一个model下载入口，然后直接指向阿里云的os路径，对应的文件夹以下发给cpodmanager时给的job的uuid作为同一命名。前端目前会把原监控按钮改为模型结果下载，然后点击跳转到阿里云的os路径下
