### ISSUE TITLE
【系统改进】清理运行结束的 MPIJob

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#234]
**背景**
目前运行结束后的 mpijob pods 残留在名字空间内
这些不应该被立即删除，但是在足够长时间后应该被删除

![image](https://github.com/NascentCore/3k/assets/142474494/06787bd9-7e03-4784-8fd0-d4fbd2b1c5f9)
![image](https://github.com/NascentCore/3k/assets/142474494/8e2f3a7f-5e03-4319-b61d-91452a1ed746)

**系统改进提议和目的**
定期检查生命末期（nomorechange）的 mpijob pods 等，如果其生存期长于某个界限，即将他们删除掉

**是否考虑过其他解决方案**
无

**Comment by congpeiqing** [comment]
目前的实现是所有任务成功完成的任务都会在1分钟之内删掉，失败的任务暂没有删除。 如果后面需要改进，再打开issue.
