### ISSUE TITLE
【安全问题】云市场限制非已知 cpodmanager 联入，在算力源注册功能完成后，须提供相应的限制

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#243]
目前任何人都可以接入 cloud.nascentcore.ai
应该只有注册过的算力源用户才能调用，因此需要向用户发放证书、或者提供 API Key

**Comment by jimgreat666** [comment]
这个我可以简单说下以前的做法作为参考：，后端提供端口：gettoken（参数：用户id）以json格式返回新生成的token，，，调用者需要保存此token，，下次发起函数调用时，在发起http请求时带上此token，，服务端这边会对此token鉴权，若已失效，会返回401错误，，，调用者当出现401错误时，需要重新调用gettoken函数得到新的token，然后再携带token发起http功能函数。
不过目前代码开源，，别人也按照此模式调用，约等于直接调用了
