### ISSUE TITLE
【系统改进】引入 volcano 完成 gang scheduling

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#257]
**背景**
如之前发现的 bug，我们目前使用的调度器来自 k8s 原生，不支持 gang scheduling
https://github.com/NascentCore/3k/issues/204
造成任务占据 gpu 资源无法释放，影响后续任务提交

**系统改进提议和目的**
使用 volcano 并改动 cpodmanager 创建与之对应的任务 YAML 

**是否考虑过其他解决方案**
无

**Comment by cairong-ai** [comment]
- 已调整 gang scheduling 为 volcano
- 离线部署包中已加入 volcano 相关的镜像
- 已增加 cpod 部署时自动安装 volcano
