### ISSUE TITLE
【DevOps】cpodmanager自动构建的镜像不可用

### ISSUE THREAD

**Issue by cairong-ai** [NascentCore/3k#310]
**背景**
添加cpodmanager自动构建后，构建的镜像拉起pod后提示 x509 错误
![img_v3_025a_8e26bf18-79f2-4e47-a925-97ce0a21f3fg](https://github.com/NascentCore/3k/assets/146914987/a9d2aa99-23f7-4568-80c1-4a832586fc97)

**改动**

**其他备选**

**Comment by congpeiqing** [comment]
报错的镜像是哪个？
另外，编译的代码和 构建镜像使用的Dockerfile在哪儿能看到？  
@cairong-ai

**Comment by congpeiqing** [comment]
经过调研，使用Alpine做为基础镜像没有问题。
使用目前自动化构建所使用的Ubuntu作为基础镜像会出现上述问题。
解决方案：替换自动化构建所使用的基础镜像。 
可以参照
https://github.com/NascentCore/3k/blob/main/cmd/cpodmanager/Dockerfile
