### ISSUE TITLE
【BUG】创建训练任务没有检查GPU选项

### ISSUE THREAD

**Issue by guochenshu** [NascentCore/3k#333]
**复现步骤**
复现步骤如下：
1. 创建任务不选择GPU型号

**预期的正确/合理行为**
拦截请求，提示选择GPU

**提供截图**
![image](https://github.com/NascentCore/3k/assets/152252984/37b21081-e165-4577-8051-31acd798e7e5)

**提供其他资料**
日志、网页链接、文档链接等

**Comment by yzhao-2023** [comment]
> 这个当日排查过，cpodmanager没有收到下发的任务，应该是 @jimgreat666 少做了参数检查

没有下发任务为什么会显示“运行中”？是不是应该增加一个任务状态“待下发”

> 是的，这个还没有到Cpod Manager。 不过检查还是应该做的。

CPodManager 必须做检查，否则用户通过三千平台直接提交任务，还是会碰到这个问题
当然我不清楚目前 cpodmananger 这种场景下的行为是什么

@congpeiqing 你需要调研一下，或者脑子里搞清楚是什么问题，然后看看如何解决
