### ISSUE TITLE
【DevOps】设置 codecov

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#456]
为 3k 平台配置 codecov
参考 DLRover repo
https://github.com/search?q=repo%3Aintelligent-machine-learning%2Fdlrover%20codecov&type=code

**Comment by zhc1984** [comment]
![aab61411-a55b-4813-9256-4c9218079ce1](https://github.com/NascentCore/3k/assets/155932688/5a61d3b9-e050-40e4-8b8a-67c7b8eb1785)

https://github.com/NascentCore/3k/pull/457

**Comment by yzhao-2023** [comment]
![image](https://github.com/NascentCore/3k/assets/142474494/8b839e38-7c4b-4ca0-a7bc-eb33ac690f15)
点右下角的 close with comment 关闭这个 issue
