### ISSUE TITLE
【DevOps】镜像预热工作过程记录

### ISSUE THREAD

**Issue by zhc1984** [NascentCore/3k#469]
**背景**
提升训练速度

**改动**
增加镜像预热能力

Host lanyun
    HostName [219.159.22.20](http://219.159.22.20/)
    Port 60022
    IdentityFile ~/.ssh/zc.key
    User zc
这是 master 集群的登录信息
这个集群是LY提供的机器，目前有 master、worker1、worker2 三台机器，worker2 是一个单节点集群，用于开发测试，master、worker1 是生产集群，对外提供测试服务都用这个

参考文档：https://d7y.io/zh/docs/next/getting-started/quick-start/kubernetes/

验证预热接口

![img_v3_0270_37f8dda2-64ec-43fd-92c0-7f95f0045f7g](https://github.com/NascentCore/3k/assets/155932688/9a8fbc3d-c3b6-40b4-bcb5-31dd19541779)

```
kubectl --namespace dragonfly-system port-forward service/dragonfly-manager 8081:8080

curl --location --request POST 'http://127.0.0.1:8081/api/v1/jobs' \
--header 'Content-Type: application/json' \
--data-raw '{
    "type": "preheat",
    "args": {
        "type": "image",
        "url": "https://ghcr.io/v2/dragonflyoss/dragonfly2/manager/manifests/v2.0.5"
    }
}'

```
返回结果

```
{"id":4,"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","is_del":0,"task_id":"group_5a66ef31-ab88-4abe-8254-6e163dc0cfb1","bio":"","type":"preheat","state":"PENDING","args":{"filter":"","headers":null,"password":"","platform":"","tag":"","type":"image","url":"https://ghcr.io/v2/dragonflyoss/dragonfly2/manager/manifests/v2.0.5","username":""},"result":null,"user_id":0,"user":{"id":0,"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","is_del":0,"email":"","name":"","avatar":"","phone":"","state":"","location":"","bio":"","configs":null},"seed_peer_clusters":null,"scheduler_clusters":[{"id":1,"created_at":"2023-12-12T13:28:05Z","updated_at":"2023-12-12T13:28:05Z","is_del":0,"name":"cluster-1","bio":"","config":{"candidate_parent_limit":4,"filter_parent_limit":40},"client_config":{"concurrent_piece_count":4,"load_limit":50},"scopes":{},"is_default":true,"seed_peer_clusters":null,"schedulers":null,"peers":null,"jobs":null}]}

````

zc@master:~$ curl --request GET 'http://127.0.0.1:8081/api/v1/jobs/1'

{"id":1,"created_at":"2023-12-14T04:23:12Z","updated_at":"2023-12-14T04:43:20Z","is_del":0,"task_id":"group_f7b4382e-6fff-44b4-abf8-9499194c08b0","bio":"","type":"preheat","state":"FAILURE","args":{"filter":"","headers":null,"password":"","platform":"","tag":"","type":"image","url":"https://sxwl-registry.cn-beijing.cr.aliyuncs.com/v2/sxwl-ai/ansible/manifests/test","username":""},"result":{"CreatedAt":"2023-12-14T04:23:12.993016658Z","GroupUUID":"group_f7b4382e-6fff-44b4-abf8-9499194c08b0","JobStates":[{"CreatedAt":"2023-12-14T04:23:12.993016658Z","Error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","Results":null,"State":"FAILURE","TTL":0,"TaskName":"preheat","TaskUUID":"task_171f0f60-9ad1-4d77-a2e1-af6700fb9a81"},{"CreatedAt":"2023-12-14T04:23:12.993353638Z","Error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","Results":null,"State":"FAILURE","TTL":0,"TaskName":"preheat","TaskUUID":"task_8ce29994-10dd-458c-862b-de01540204f1"},{"CreatedAt":"2023-12-14T04:23:12.993545763Z","Error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","Results":null,"State":"FAILURE","TTL":0,"TaskName":"preheat","TaskUUID":"task_fe030452-d505-450f-b15e-658b4706ef58"}],"State":"FAILURE"},"user_id":0,"user":{"id":0,"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","is_del":0,"email":"","name":"","avatar":"","phone":"","state":"","location":"","bio":"","configs":null},"seed_peer_clusters":[],"scheduler_clusters":[{"id":1,"created_at":"2023-12-12T13:28:05Z","updated_at":"2023-12-12T13:28:05Z","is_del":0,"name":"cluster-1","bio":"","config":{"candidate_parent_limit":4,"filter_parent_limit":40},"client_config":{"concurrent_piece_count":4,"load_limit":50},"scopes":{},"is_default":true,"seed_peer_clusters":null,"schedulers":null,"peers":null,"jobs":null}]}

**其他备选**
其他还有什么方案？

**Comment by yzhao-2023** [comment]
这个是记录任务的目标、方案等
工作记录放在飞书文档，方便点评和分享

**Comment by zhc1984** [comment]
问题已经通过新的方案解决，详见：https://tricorder.feishu.cn/wiki/DAA6w7FbViebXakoeaZc2iYhnbg?from=from_copylink
