### ISSUE TITLE
【任务】gemma

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#608]
**目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

**实施方案**
> 详细提供该系统改进的实施方案

- https://huggingface.co/google/gemma-7b-it
- Gemma 加入到推理的管线上 https://blog.google/technology/developers/gemma-open-models/
  - 推理使用 tensorrt-llm，微调后模型推理尽量使用 tensorrt-llm
- Gemma 微调支持

**Comment by donggangcj** [comment]
目前3k推理已完成：

需要和算想云集成；
微调

**Comment by cairong-ai** [comment]
gemma-2b-it 无代码微调已支持
算想云侧需添加配置

**Comment by yzhao-2023** [comment]
算想云 benchmark 微调的效果：同样的微调数据记录微调完成的时间

**Comment by yzhao-2023** [comment]
添加示例，编写文档，然后就完成了
