### ISSUE TITLE
【任务】mixtral-7b & mistral-7b

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#609]
**目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

**实施方案**
> 详细提供该系统改进的实施方案

- https://huggingface.co/google/gemma-7b-it
- Mixtral 加入到推理的管线上 https://huggingface.co/docs/transformers/en/model_doc/mixtral
  - 推理使用 tensorrt-llm，微调后模型推理尽量使用 tensorrt-llm
- Mixtral 微调支持

**Comment by donggangcj** [comment]
目前3k推理已完成：
- 需要和算想云集成；
- 微调

**Comment by cairong-ai** [comment]
mistral-7b

**Comment by yzhao-2023** [comment]
算想云 benchmark 微调的效果：同样的微调数据记录微调完成的时间

**Comment by sxwl-donggang** [comment]
目前 mixtral-8*7b 在3090 6卡微调已经验证通过，下一步加入到finetune 支持列表中

**Comment by yzhao-2023** [comment]
https://www.deepspeed.ai/tutorials/flops-profiler/
@sxwl-donggang @tierbicisaigao

**Comment by yzhao-2023** [comment]
完成了已经，下一步编写 mixtral 微调+推理的示例
示例要确认：
1. 微调的效果，也就是微调前后推理的示例能看出微调数据对模型行为的改变
2. 确认 RDMA 使用
