### ISSUE TITLE
【任务】LLM 运行性能评测

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#611]
**目标**

  [] 编写 LLM 推理性能评测代码，评测指标：Time To First Token (TTFT)、Time Per Output Token (TPOT)、Latency、Throughput；这几项性能指标的解释：https://www.databricks.com/blog/llm-inference-performance-engineering-best-practices

**实施方案**
> 详细提供该系统改进的实施方案

**Comment by cairong-ai** [comment]
![image](https://github.com/NascentCore/3k/assets/146914987/77efb050-ebdd-495a-9e01-417cb6b565a7)
