### ISSUE TITLE
【功能需求】算想云全局存储

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#616]
**背景**
> 描述系统现有的状况和相关的具体信息

**这个功能需求是解决什么问题？**
> 描述问题的具体场景，以及想要达到的效果

**解决方案**
> 列举目前考虑的可选解决方案

**Comment by guochenshu** [comment]
1. 基于oss作为存储仓库
2. 仓库分为公开资源和用户资源
3. 算想云提供接口查询仓库中的公开资源和用户私有资源
4. 改造训练任务流程，本地集群缺少资源（数据集或模型），portalSync自动下载后创建训练任务

**Comment by yzhao-2023** [comment]
提供示例

**Comment by guochenshu** [comment]
finetune 和 inference缺少自动下载的逻辑，需要补一下
