### ISSUE TITLE
【任务】PC 大模型技术方案

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#617]
**目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

PC 上部署流行的大模型，并且能提供可用的产品体验
1. 我们能够提供的大模型列表
2. 以上大模型运行性能指标：token per second、time to first token、延迟

**实施方案**
> 详细提供该系统改进的实施方案

**Comment by yzhao-2023** [comment]
@glen-nascentcoreai 提供文档链接

**Comment by glen-nascentcoreai** [comment]
https://tricorder.feishu.cn/wiki/Jz2UwYQ37igUYukxjCAcllvonhg

**Comment by yzhao-2023** [comment]
不再做了，目前不适合我们的技术背景
