### ISSUE TITLE
【任务】提供 GHY 模型仓库 WebUI demo

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#642]
**目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

1. GHY 类似 LY，是 GPU 算力运营商
2. 需要云管系统来管理多个智算集群
3. 需要云平台来提供大模型云服务
4. 需要模型仓库来提供用户使用的入口
5. 需要计量系统来：想清楚怎么区分不同用户，增加一个 user label； @cairong-ai 看一下如何在 portalsync 的 user 写入 cpod cr label

**实施方案**
> 详细提供该系统改进的实施方案

**Comment by cairong-ai** [comment]
1. 暂时通过增加user label区分不同用户使用的资源计量，user label 已增加
2. webui 已增加
