### ISSUE TITLE
【系统改进】预置模型的功能支持

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#643]
**现状**
> 当前的现状是什么（当前的行为、设计、架构）？

只列举了模型，但是该模型是否支持微调/推理没有说明：

**系统改进的目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

![image](https://github.com/NascentCore/3k/assets/142474494/63b2c624-83e6-4905-9d0c-49cc4e69316f)

**系统改进的实施方案**
> 详细提供该系统改进的实施方案

**Comment by sxwl-donggang** [comment]
done;
