### ISSUE TITLE
【功能需求】Jupyter 开发和启动任务

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#697]
**背景**
> 描述系统现有的状况和相关的具体信息

现在仅能启动 jupyter 工作环境，但是用户代码无法在后续使用

**这个功能需求是解决什么问题？**
> 描述问题的具体场景，以及想要达到的效果

让 jupyter 代码用于后续任务

**解决方案**
> 列举目前考虑的可选解决方案

1. 在 jupyter 编写代码，并挂载大模型，使得用户可以在 jupyter 里写代码使用挂载的模型；考虑算想云、算想三千两种场景工作方式
2. 保存代码
3. 构建镜像，包含用户代码（可以考虑直接 save 运行中的容器镜像）
4. 用该镜像启动任务，与现有 workflow 对接

需要添加一个启动 jupyter 的流程和对应的 webui @guochenshu @zhoujie16 

后端打包镜像需要使用定制的 jupyter 镜像，然后保存镜像，这个我们以前讨论类似 autodl 的产品有讨论 @cairong-ai 

流程关联需要 @sxwl-donggang cpodoperator 来串连 (Edited)；目前已知：
1. CpodOperator 使用定制参数来启动 Jupyter 服务（使用算想未来自制的镜像、挂载大模型，等等）

**讨论**
是否要有容器镜像保存
1. 目前不考虑保存工作容器镜像
2. 只面向通过 Jupyter 编写代码、打包镜像、执行这样的工作流
3. 下一步是提供类 autodl jupyter 工作空间保存的功能
4. kubeflow 给 Jupyter 挂载 volume 来做持久化

后续设计记录在：https://tricorder.feishu.cn/wiki/LhSHwGxxriBC5fkGoilcICpVnzd

**Comment by cairong-ai** [comment]
## 方案
1. 用户可自助创建、删除 JupyterLab 实例
2. JupyterLab 实例创建后可通过 WebUI 直接进入 notebook 页面
3. 在 JupyterLab notebook 中开发调度通过后，可基于该实例内的代码构建镜像
4. 构建后的镜像可直接用于提交 cpodjob 任务
5. 构建后的镜像可直接在 WebUI 上进行查询、删除

## 进展
1. 创建、删除 JupyterLab 实例后端API以及流程已调试通过
2. 前端页面还在联调过程中

## 问题
- 目前构建镜像的功能是由 scheduler 直接调用 3kctl server 接口进行的
- 私有化部署场景下没问题，但在算想云场景下无法直接调用

**Comment by cairong-ai** [comment]
1. 整体流程测试通过
2. 前端UI联调已完成

**Comment by yzhao-2023** [comment]
本周完成最基本的创建实例（选择资源、模型、存储卷）
其他功能日后补齐
已实现的额外功能（如构建镜像）先予以保留（未来看情况再定）
@刘朝阳 @cairong-ai 交流一下算法工程师使用的需求

**Comment by yzhao-2023** [comment]
- [ ] 在算想云中显示 JupyterLab 功能
![image](https://github.com/NascentCore/3k/assets/142474494/67ce6731-f440-4ee9-b336-a2628c550bee)
@zhoujie16

**Comment by cairong-ai** [comment]
![image](https://github.com/NascentCore/3k/assets/146914987/857990a3-df17-47e6-be89-b2465ab4c690)
