### ISSUE TITLE
【任务】Mixtral 8*7B 示例

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#698]
**目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

确认 Mixtral 8*7Bf
1. 微调的效果，也就是微调前后推理的示例能看出微调数据对模型行为的改变
用微调的案例考核推理实例；也就是用微调的示例、原装不变用于推理提问

2. 确认卡间通信使用 DMA；确保最大限度使用硬件资源

**实施方案**
> 详细提供该系统改进的实施方案

TBA

**Comment by sxwl-donggang** [comment]
1.  8*7B推理已经提供给用户
2. 目前推理使用的是单机8卡，没有使用RDMA设备，所以无法验证
3. SFT效果还在验证

**Comment by yzhao-2023** [comment]
> 目前推理使用的是单机8卡，没有使用RDMA设备，所以无法验证

要提供文档，是否使用卡间通信的直联通信是开源用户比较困惑的地方

**Comment by yzhao-2023** [comment]
取消在 mixtral 上展示微调效果的目标，改为 LLaMA2（转入 https://github.com/NascentCore/3k/issues/732）

**Comment by sxwl-donggang** [comment]
已经完成
