### ISSUE TITLE
【任务】LLaMA2 微调示例

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#732]
来自 https://github.com/NascentCore/3k/issues/698
Mixtral 微调很慢，改为用 LLaMA2 作为示例的基础模型

**目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

**实施方案**
> 详细提供该系统改进的实施方案

**Comment by sxwl-donggang** [comment]
Mixtral已完成
