### ISSUE TITLE
【功能需求】上传本地模型到算想云

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#735]
**背景**
> 描述系统现有的状况和相关的具体信息

现有场景下用户无法上传模型

**这个功能需求是解决什么问题？**
> 描述问题的具体场景，以及想要达到的效果

用户本地研发的模型，希望部署到算想云上

**解决方案**
> 列举目前考虑的可选解决方案

命令行上传：指定名称，私有数据
上传后显示在用户自有的模型仓库列表中
对接其他功能组件

**Comment by cairong-ai** [comment]
1. 已在3kctl中添加上传模型、数据集功能
- 将模型、数据集复制到3kctl所在节点
- 执行 3kctl 命令上传模型或数据集
```
3kctl upload model --name=myself/model-name --dir=/path/to/model-name
3kctl upload dataset --name=myself/dataset-name --dir=/path/to/dataset-name
```
