### ISSUE TITLE
【任务】编写算想云产品文档

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#825]
**目标**
> 本提议所希望看到的改动的目标是什么？

为开源社区开发者用户提供产品手册；服务用户上手算想云
与算想三千不同的是，算想云有算力源加入的功能；需要额外描述

> 这些改动能带来什么价值？

让开源社区用户直接上手使用

**实施方案**
> 详细提供该系统改进的实施方案

TBD

**Comment by guochenshu** [comment]
https://tricorder.feishu.cn/wiki/TEnFwKhJIi5mzYkcVxacToxanYb

**Comment by yzhao-2023** [comment]
@yzhao-2023 阅读修改一轮

**Comment by guochenshu** [comment]
面向算力用户的算想云产品手册 https://tricorder.feishu.cn/wiki/TEnFwKhJIi5mzYkcVxacToxanYb
面向算力源的算想云产品手册 https://tricorder.feishu.cn/wiki/RAOEwRJ3ei4RMpkfGGCcNjCmn0f
