### ISSUE TITLE
【系统改进】三千平台多用户基于 namespace 隔离

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#828]
**现状**
> 当前的现状是什么（当前的行为、设计、架构）？

cpodoperator 启动任务都位于同一个 namespace，不同用户的任务共享该 namespace，带来安全隐患

**系统改进的目标**
> 本提议所希望看到的改动的目标是什么？

基于 namespace 隔离

> 这些改动能带来什么价值？

基本安全和隐私保护

**系统改进的实施方案**
> 详细提供该系统改进的实施方案

TBD

**Comment by sxwl-donggang** [comment]
portsync代码开发自测中

**Comment by yzhao-2023** [comment]
* 三千平台的系统所在 namespace：三千平台系统组件
* 公共 namespace：公共模型、数据集
* 用户 namespace：私有模型、数据集、checkpoint、训练任务、推理任务

公共 namespace 里的公共模型、数据集都可以被用户 namespace 里的任务访问

开发主体工作基本完成，正在测试中

**Comment by sxwl-donggang** [comment]
联调遇到juicefs csi 同一个 pod挂载两个 static pvc问题，目前已定位到问题是 pc volumehandle字段需要唯一。
