### ISSUE TITLE
【系统改进】说明 GPU 调度的具体行为

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#878]
**现状**
> 当前的现状是什么（当前的行为、设计、架构）？

现在 GPU 调度只要求用户指定总量 C，然后 C/8 计算出节点数目，然后进行调度

**系统改进的目标**
> 本提议所希望看到的改动的目标是什么？
> 这些改动能带来什么价值？

希望能完整说明目前 GPU 调度的行为，并确保符合用户预期

**系统改进的实施方案**
> 详细提供该系统改进的实施方案

**Comment by sxwl-donggang** [comment]
目前行为是，用户指定worker数量（一个 worker对应一个节点）以及 GPU总数，每个节点 GPU数量= GPU总数/worker数，如用户指定使用 8GPU,2个worker，则每个节点需要分配 4 个 GPU。
