### ISSUE TITLE
【功能需求】用户任务日志提供给用户查看

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#882]
**背景**
> 描述系统现有的状况和相关的具体信息
目前任务详情中没有运行日志展示，用户无法直接查看任务执行日志

**这个功能需求是解决什么问题？**
> 描述问题的具体场景，以及想要达到的效果

**解决方案**
> 列举目前考虑的可选解决方案
将loki日志链接添加至『任务详情』中，用户可以点击直接打开查看任务日志

**Comment by cairong-ai** [comment]
已上线测试版『任务详情』，包含：
- 任务日志
- GPU使用情况
- [ ] 待添加更多指标
