### ISSUE TITLE
【任务】系统资源看板内嵌到页面上，与 TensorBoard 一致

### ISSUE THREAD

**Issue by yzhao-2023** [NascentCore/3k#887]
**目标**
> 本提议所希望看到的改动的目标是什么？

将系统资源看板内嵌到页面上

> 这些改动能带来什么价值？

与 TensorBoard 一致

**实施方案**
> 详细提供该系统改进的实施方案

TBD

**Comment by cairong-ai** [comment]
已规划并上线测试版『任务详情』，此处『系统资源看板』入口暂时关闭

**Comment by cairong-ai** [comment]
已调整 Tensorboard 为新开页面，与 系统资源看板 保持一致
